WIP - T364134 New Media Viewer Experience
wikimedia/wikipedia-preview pull request #216
Opened 2024-06-06 07:12 UTC by hueitan

Phabricator: https://phabricator.wikimedia.org/T364134
Demo: -

2024-06-12 15:02 UTC, stephanebisson submitted a review, later dismissed
If you toggle the network to "slow 3G", the image description appears first, right below the image loading state in the middle of the page and then shifts down when the image is loaded. I would recommend only showing the image description when the image is loaded to avoid the shift.

2024-06-14 20:02 UTC, stephanebisson requested changes

2024-06-17 07:21 UTC, hueitan commented on src/gallery/slider.js
> +				<a href="${ link }" class="${ prefixClassname }-item-attribution-info-link" target="_blank">Learn more ${ getLinkIconSvg() }</a>
Done.

2024-06-17 19:10 UTC, stephanebisson requested changes
When hovering over the icon next to "learn more" I get the following error in the console:
"Uncaught TypeError: e.target.className.indexOf is not a function"

2024-06-18 09:38 UTC, hueitan commented
> When hovering over the icon next to "learn more" I get the following error in the console: "Uncaught TypeError: e.target.className.indexOf is not a function"

Good catch, fixed now.

2024-06-18 17:33 UTC, stephanebisson approved these changes

2024-06-20 17:33 UTC, stephanebisson commented on style/gallery.less
> +					bdi {
I don't think bdi should be used for styling. There must be a div or span with a meaningful class nearby.

2024-06-25 14:19 UTC, merged