avoid duplication of the image info in slider component
wikimedia/wikipedia-preview pull request #83
Opened 2020-10-26 12:53 UTC by hueitan

Phabricator Ticket : -

![image](https://user-images.githubusercontent.com/2560096/97174550-88a34e80-1792-11eb-9cf6-138143c1b510.png)

2020-10-26 23:49 UTC, medied requested changes

2020-10-26 23:49 UTC, medied commented on src/gallery/slider.js
> +						captionElement = item.querySelector( `.${prefixClassname}-item-captiond` )
Small typo here: `captiond`

2020-10-27 08:35 UTC, hueitan commented on src/gallery/slider.js
> +						captionElement = item.querySelector( `.${prefixClassname}-item-captiond` )
arrrr... thanks! fix now.

2020-10-27 16:05 UTC, medied approved these changes

2020-10-27 16:07 UTC, medied commented
Looks good, merging now as this will be useful for the [T262371](https://phabricator.wikimedia.org/T262371) that I'm working on now

2020-10-27 16:07 UTC, merged